# Generated by Django 3.1.4 on 2020-12-15 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('first_name', models.CharField(max_length=30, verbose_name='Name: ')),
                ('last_name', models.CharField(max_length=40, verbose_name='Surname: ')),
                ('gender', models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='Gender: ')),
                ('address', models.CharField(max_length=1024, verbose_name='Address: ')),
                ('biography', models.TextField(verbose_name='Biograpyhy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
