# Generated by Django 3.1.4 on 2020-12-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20201207_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='media/story_images', verbose_name='Sekil'),
        ),
    ]
